---
title: 'Fantasy Football Receiving Stats & Opportunities'
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)
library(nflfastR)
library(tidyverse)
library(htmltools)
library(htmlwidgets)
library(reactable)
```

```{r data}
### read in file for scoring updated through week 7
advanced_receiving_stats <- read.csv("WR_and_TE_scoring_wk7.csv")

### if you want to pull the latest data, run the following below, otherwise use the data above:
# nfl_data_2020 <- readRDS(url('https://raw.githubusercontent.com/guga31bb/nflfastR-data/master/data/play_by_play_2020.rds'))
# 
# roster <- fast_scraper_roster(2020)
# 
# decoded_nfl_data_2020 <- nfl_data_2020 %>%
#   decode_player_ids()
# 
# joined <- decoded_nfl_data_2020 %>%
#   filter(pass_attempt == 1 &
#            two_point_attempt == 0 &
#            !is.na(receiver_id)) %>%
#   select(week, posteam, desc, game_id, play_id, receiver, receiver_id, complete_pass, incomplete_pass, yards_gained, touchdown, air_yards, yards_after_catch, yardline_100, fumble_lost) %>%
#   left_join(roster, by = c('receiver_id' = 'gsis_id'))

### weekly data
# advanced_receiving_stats <- joined %>%
#   mutate(
#     yards = ifelse(yardline_100==air_yards, yardline_100, yards_gained),
#     reception = ifelse(complete_pass == 1, 1, 0),
#     target = 0,
#     game_played = 0
#   )  %>%
#   group_by(week, game_id, receiver) %>%
#   mutate(game_played = ifelse(row_number() == 1, 1, 0)) %>%
#   ungroup %>%
#   group_by(week, game_id, play_id, receiver) %>%
#   mutate(target = ifelse(row_number() == 1, 1, 0)) %>%
#   ungroup() %>%
#   group_by(week, posteam, receiver, position) %>%
#   summarize(
#     games = sum(game_played, na.rm = TRUE),
#     targets = sum(target, na.rm = TRUE),
#     rec = sum(reception, na.rm = TRUE),
#     yards = sum(ifelse(reception == 1, yards, 0), na.rm = TRUE),
#     TD = sum(touchdown, na.rm = TRUE),
#     air_yards = sum(air_yards, na.rm = TRUE),
#     fumbles = sum(fumble_lost, na.rm = TRUE)
#   ) %>%
#   ungroup() %>%
#   mutate(fpts = (rec + yards/10 + TD*6) - fumbles*2) %>%
#   group_by(week, posteam) %>%
#   mutate(team_targets = sum(targets),
#          team_air_yards = sum(air_yards)) %>%
#   group_by(week, receiver, position, .add = TRUE) %>%
#   mutate(target_share = targets/team_targets,
#          air_yards_share = air_yards/team_air_yards) %>%
#   mutate(WOPR = 1.5*target_share + 0.7*air_yards_share) %>%
#   filter(position %in% c("WR", "TE")) %>%
#   ungroup()
#  
# write.csv(advanced_receiving_stats, "WR_and_TE_scoring_wk7.csv")

### weekly stats table for drilldown
weekly_stats <- advanced_receiving_stats %>%
  # mutate(`TGT SHARE` = round(target_share*100,1),
  #        `AIR SHARE` = round(air_yards_share*100,1)) %>% 
  select(
    Player = receiver,
    WEEK = week,
    `TGT SHARE` = target_share,
    `AIR SHARE` = air_yards_share,
    TGT = targets,
    REC = rec,
    YDS = yards,
    AIR = air_yards,
    TDS = TD,
    PTS = fpts
  )

top100_data <- advanced_receiving_stats %>%
  group_by(receiver, posteam, position) %>%
  summarise(
    games_played = sum(games, na.rm = TRUE),
    total_fpts = sum(fpts, na.rm = TRUE),
    avg_targets = mean(targets, na.rm = TRUE),
    avg_rec = mean(rec, na.rm = TRUE),
    avg_yards = mean(yards, na.rm = TRUE),
    avg_air_yards = mean(air_yards, na.rm = TRUE),
    avg_touchdowns = mean(TD, na.rm = TRUE),
    target_share = round(mean(target_share, na.rm = TRUE), 3),
    air_share = round(mean(air_yards_share, na.rm = TRUE), 3),
    WOPR = round(mean(WOPR, na.rm = TRUE), 3)
  ) %>%
  ungroup() %>%
  mutate(rank = rank(-total_fpts, ties.method = "first")) %>%
  filter(rank <= 100)

top_100_avg_fpts <- top100_data %>%
  summarize(avg_fpts = round(sum(total_fpts)/sum(games_played),2))

top100_data_final <- top100_data %>%
  mutate(
    WOPR = ntile(WOPR, 4),
    target_share_ntile = ntile(target_share, 4),
    air_share_ntile = ntile(air_share, 4),
    avg_targets = format(avg_targets, digits = 1, nsmall = 1),
    avg_rec = format(avg_rec, digits = 1, nsmall = 1),
    avg_yards = format(avg_yards, digits = 1, nsmall = 1),
    avg_air_yards = format(avg_air_yards, digits = 1, nsmall = 1),
    avg_touchdowns = format(avg_touchdowns, digits = 1, nsmall = 1),
    avg_fpts = round(total_fpts/games_played,2)
  ) %>%
  mutate(
    avg_fpts_diff = round(avg_fpts-top_100_avg_fpts$avg_fpts,2),
    WOPR = case_when(WOPR == 1 ~ "D",
                     WOPR == 2 ~ "C",
                     WOPR == 3 ~ "B",
                     WOPR == 4 ~ "A",
                     TRUE ~ "NA")
  ) %>%
  # mutate(
  #   `Target Share` = paste0(format(
  #     100 * target_share, digits = 1, nsmall = 1
  #   ), "%"),
  #   `Air Share` = paste0(format(
  #     100 * air_share, digits = 1, nsmall = 1
  #   ), "%")
  # ) %>%
  select(
    Player = receiver,
    Position = position,
    Team = posteam,
    WOPR,
    `Target Share` = target_share,
    target_share_ntile,
    air_share_ntile,
    `Air Share` = air_share,
    avg_targets,
    avg_rec,
    avg_yards,
    avg_air_yards,
    avg_touchdowns,
    avg_fpts,
    avg_fpts_diff
  )
```


```{r table}
# Avg points vs top 100 positive and negative values chart
avg_pts_vs_top_100_chart <- function(label,
                                     value,
                                     height = "12px",
                                     pos_fill = "#1a9641",
                                     neg_fill = "#d7191c") {
  neg_chart <- div(style = list(flex = "1 1 0"))
  pos_chart <- div(style = list(flex = "1 1 0"))
  max_value <- abs(max(top100_data_final$avg_fpts_diff))
  width <- paste0(abs(value / max_value) * 100, "%")
  
  if (value < 0) {
    bar <-
      div(style = list(
        background = neg_fill,
        width = width,
        height = height
      ))
    chart_labels <-
      div(style = list(
        display = "flex",
        alignItems = "center",
        justifyContent = "flex-end"
      ),
      label)
    chart <-
      div(style = list(
        display = "flex",
        alignItems = "center",
        justifyContent = "flex-end"
      ),
      bar)
    neg_chart <- tagAppendChildren(neg_chart, chart, chart_labels)
  } else {
    bar <-
      div(style = list(
        background = pos_fill,
        width = width,
        height = height
      ))
    chart_labels <-
      div(
        style = list(
          display = "flex",
          alignItems = "center",
          justifyContent = "flex-start"
        ),
        label
      )
    chart <-
      div(style = list(display = "flex", alignItems = "center"), bar)
    pos_chart <- tagAppendChildren(pos_chart, chart, chart_labels)
  }
  div(style = list(display = "flex"), neg_chart, pos_chart)
}


# nest_table <- function(index){
#   # filter to just the complaint_type of interest
#   in_data <- wide_data %>% 
#     filter(complaint_type == unique(wide_data$complaint_type)[index]) %>% 
#     select(complaint_type, everything())
#   
#   htmltools::div(
#     style = list("padding: 30px", "align: right"),
#     reactable(
#       defaultSortOrder = "desc",
#       in_data,
#       defaultColDef = colDef(
#         minWidth = 40,
#         style = function(value){
#           if (!is.numeric(value)) return()
#           tall_in_data <- in_data %>% 
#             pivot_longer(cols = Jan:Dec, 
#                          names_to = "months", 
#                          values_to = "values") %>% 
#             pull(values)
#           
#           normalized <- (value - min(tall_in_data)) / (max(tall_in_data) - min(tall_in_data))
#           color <- green_pal(normalized)
#           list(background = color)
#         }),
#       columns = list(
#         year = colDef("Year"),
#         complaint_type = colDef("",width = 250))))
# }
make_color_pal <- function(colors, bias = 1) {
  get_color <- colorRamp(colors, bias = bias)
  function(x)
    rgb(get_color(x), maxColorValue = 255)
}

off_rating_color <-
  make_color_pal(c("#e6fbea","#b0f2bc","#67dba5","#4cc8a3"))


table <-
  reactable(
    top100_data_final,
    paginationType = "simple",
    wrap = FALSE,
    minRows = 10,
    showPageSizeOptions = TRUE,
    searchable = TRUE,
    highlight = TRUE,
    showSortIcon = FALSE,
    compact = TRUE,
    defaultSorted = "avg_fpts_diff",
    defaultSortOrder = "desc",
    defaultColDef = colDef(
      headerClass = "header colheader",
      
      ),
    columnGroups = list(
      colGroup(
        name = "Averages per Game",
        columns = c(
          "avg_targets",
          "avg_rec",
          "avg_yards",
          "avg_air_yards",
          "avg_touchdowns",
          "avg_fpts"
        ),
        headerClass = "groupheader"
      )
    ),
    ### function to drilldown player stats by week
    details = function(index) {
      weekly_stats_data <-
        filter(weekly_stats, Player == top100_data_final$Player[index]) %>% select(-Player)
      
      div(
        reactable(
        weekly_stats_data,
        outlined = TRUE,
        highlight = TRUE,
        fullWidth = FALSE,
        showSortIcon = FALSE,
        defaultColDef = colDef(
          headerClass = "header colheader",
          class = "cell number",
          # align = "right",
          minWidth = 90
        ),
        columns = list(
          WEEK = colDef(maxWidth = 55),
          `TGT SHARE` = colDef(cell = function(value) {
                paste0(format(value*100, nsmall = 1, digits = 1),"%")
          },
                style = function(value) {
            normalized <- (value - min(weekly_stats$`TGT SHARE`)) / (max(weekly_stats$`TGT SHARE`) - min(weekly_stats$`TGT SHARE`))
            color <- off_rating_color(normalized)
            list(background = color)
          }),
          `AIR SHARE` = colDef(cell = function(value) {
                paste0(format(value*100, nsmall = 1, digits = 1),"%")
          },
          style = function(value) {
            normalized <- (value - min(weekly_stats$`AIR SHARE`)) / (max(weekly_stats$`AIR SHARE`) - min(weekly_stats$`AIR SHARE`))
            color <- off_rating_color(normalized)
            list(background = color)
          }),
          TGT = colDef(style = function(value) {
            normalized <- (value - min(weekly_stats$TGT)) / (max(weekly_stats$TGT) - min(weekly_stats$TGT))
            color <- off_rating_color(normalized)
            list(background = color)
          }),
          REC = colDef(style = function(value) {
            normalized <- (value - min(weekly_stats$REC)) / (max(weekly_stats$REC) - min(weekly_stats$REC))
            color <- off_rating_color(normalized)
            list(background = color)
          }),
          YDS = colDef(style = function(value) {
            normalized <- (value - min(weekly_stats$YDS)) / (max(weekly_stats$YDS) - min(weekly_stats$YDS))
            color <- off_rating_color(normalized)
            list(background = color)
          }),
          AIR = colDef(style = function(value) {
            normalized <- (value - min(weekly_stats$AIR)) / (max(weekly_stats$AIR) - min(weekly_stats$AIR))
            color <- off_rating_color(normalized)
            list(background = color)
          }),
          TDS = colDef(style = function(value) {
            normalized <- (value - 0) / (4 - 0)
            color <- off_rating_color(normalized)
            list(background = color)
          }),
          PTS = colDef(style = function(value) {
            normalized <- (value - min(weekly_stats$PTS)) / (max(weekly_stats$PTS) - min(weekly_stats$PTS))
            color <- off_rating_color(normalized)
            list(background = color)
          })
        )
      ))
    },
    onClick = "expand",
    ### Add solid border between rows when sorting by Team or WOPR to distinguish groups 
          rowClass = JS("
        function(rowInfo, state) {
          const firstSorted = state.sorted[0]
          if (firstSorted && firstSorted.id === 'Team') {
            const nextRow = state.pageRows[rowInfo.viewIndex + 1]
            if (nextRow && rowInfo.row.Team !== nextRow.Team) {
              return 'last-row-border'
            }
          } else if (firstSorted && firstSorted.id === 'WOPR') {
            const nextRow = state.pageRows[rowInfo.viewIndex + 1]
            if (nextRow && rowInfo.row.WOPR !== nextRow.WOPR) {
              return 'last-row-border'
            }
          }
        }"
      ),
    columns = list(
      Player = colDef(
        name = "PLAYER",
        class = "cell",
        minWidth = 120,
        cell = function(value, index) {
          position <- top100_data_final$Position[index]
          tagList(div(style = list(
            fontWeight = 600, fontSize = 13
          ), value),
          div(style = list(fontSize = 12), position))
        }
      ),
      Position = colDef(show = FALSE),
      Team = colDef(class = "cell number",
                    minWidth = 50),
      avg_targets = colDef(
        name = "TGT",
        align = "right",
        class = "cell number",
        maxWidth = 55
      ),
      avg_rec = colDef(
        name = "REC",
        align = "right",
        class = "cell number",
        maxWidth = 55
      ),
      avg_yards = colDef(
        name = "YDS",
        align = "right",
        class = "cell number",
        maxWidth = 55
      ),
      avg_air_yards = colDef(
        name = "AIR",
        align = "right",
        class = "cell number",
        maxWidth = 55
      ),
      avg_touchdowns = colDef(
        name = "TDS",
        align = "right",
        class = "cell number",
        maxWidth = 55
      ),
      WOPR = colDef(
        name = "WOPR",
        class = "cell number",
        maxWidth = 55,
        align = "center",
        cell = function(value) {
          ### For players that were assigned a WOPR of 4 (highest rating), display an A rating, 3 = B, 2 = C, 1 = D
          color <- ifelse(value == "A",
                          "#1a9641",
                          ifelse(
                            value == "B",
                            "#a6d96a",
                            ifelse(value == "C", "#fdae61", "#d7191c")
                          ))
          ### add circle around letter grade
          div(
            class = "circle-border",
            style = list(
              background = color,
              color = "white",
              fontWeight = "bold"
            ),
            value
          )
        }
      ),
      target_share_ntile = colDef(show = FALSE),
      team_color = colDef(show = FALSE),
      air_share_ntile = colDef(show = FALSE),
      `Target Share` = colDef(
        name = "TGT SHARE",
        align = "left",
        minWidth = 85,
        class = "cell number border-left",
        ### display different levels of battery based on share of team targets
        cell = function(value, index) {
          if (top100_data_final$target_share_ntile[index] == 4) {
            icon <- tagAppendAttributes(shiny::icon("battery-full"))
            div(class = "share-columns",
                icon, paste0(" ", format(
                  100 * value, digits = 1, nsmall = 1
                ), "%"))
          } else if (top100_data_final$target_share_ntile[index] == 3) {
            icon <- tagAppendAttributes(shiny::icon("battery-three-quarters"))
            div(class = "share-columns",
                icon, paste0(" ", format(
                  100 * value, digits = 1, nsmall = 1
                ), "%"))
          } else if (top100_data_final$target_share_ntile[index] == 2) {
            icon <- tagAppendAttributes(shiny::icon("battery-half"))
            div(class = "share-columns",
                icon, paste0(" ", format(
                  100 * value, digits = 1, nsmall = 1
                ), "%"))
          } else {
            icon <- tagAppendAttributes(shiny::icon("battery-quarter"))
            div(class = "share-columns",
                icon, paste0(" ", format(
                  100 * value, digits = 1, nsmall = 1
                ), "%"))
          }
        },
        style = function(value, index) {
          if (top100_data_final$target_share_ntile[index] == 4) {
            color <- "#1a9641"
          } else if (top100_data_final$target_share_ntile[index] == 3) {
            color <- "#a6d96a"
          } else if (top100_data_final$target_share_ntile[index] == 2) {
            color <- "#fdae61"
          } else {
            color <- "#d7191c"
          }
          list(color = color, fontWeight = "bold")
        }
      ),
      `Air Share` = colDef(
        name = "AIR SHARE",
        align = "left",
        minWidth = 85,
        class = "cell number border-right",
        ### display different levels of battery based on share of air yards
        cell = function(value, index) {
          if (top100_data_final$air_share_ntile[index] == 4) {
            icon <- tagAppendAttributes(shiny::icon("battery-full"))
            div(class = "share-columns",
                icon, paste0(" ", format(
                  100 * value, digits = 1, nsmall = 1
                ), "%"))
          } else if (top100_data_final$air_share_ntile[index] == 3) {
            icon <- tagAppendAttributes(shiny::icon("battery-three-quarters"))
            div(class = "share-columns",
                icon, paste0(" ", format(
                  100 * value, digits = 1, nsmall = 1
                ), "%"))
          } else if (top100_data_final$air_share_ntile[index] == 2) {
            icon <- tagAppendAttributes(shiny::icon("battery-half"))
            div(class = "share-columns",
                icon, paste0(" ", format(
                  100 * value, digits = 1, nsmall = 1
                ), "%"))
          } else {
            icon <- tagAppendAttributes(shiny::icon("battery-quarter"))
            div(class = "share-columns",
                icon, paste0(" ", format(
                  100 * value, digits = 1, nsmall = 1
                ), "%"))
          }
        },
        style = function(value, index) {
          if (top100_data_final$air_share_ntile[index] == 4) {
            color <- "#1a9641"
          } else if (top100_data_final$air_share_ntile[index] == 3) {
            color <- "#a6d96a"
          } else if (top100_data_final$air_share_ntile[index] == 2) {
            color <- "#fdae61"
          } else {
            color <- "#d7191c"
          }
          list(color = color, fontWeight = "bold")
        }
      ),
      `avg_fpts` = colDef(
        name = "PTS",
        class = "cell number border-right",
        maxWidth = 55,
        cell = function(value) {
          label <- format(value, nsmall = 1, digits = 1)
          label
        },
        style = list(fontWeight = "bold")
      ),
      avg_fpts_diff = colDef(
        name = "Avg Pts vs Top 100",
        class = "cell number2",
        minWidth = 130,
        cell = function(value) {
          label <- if (value > 0)
            paste0("+", format(value, digits = 1, nsmall = 1))
          else
            format(value, digits = 1, nsmall = 1)
          avg_pts_vs_top_100_chart(label, value)
        }
      )
    )
  )

### Add title and subtitle to top of page above table
div(
  class = "fantasy-ratings",
  div(class = "title",
      "Top 100 WR & TE fantasy scorers in the NFL"),
  table,
  ### Add legend and source below the table
  tags$span(
    style = "color:#999",
    "Column Definitions:",
    div(
      " - WOPR = Weighted Opportunity Rating. The weighted average of a player's team target share and team air yards share, created by Josh Hermsmeyer from FiveThirtyEight. If a player has an 'A' WOPR, this means they are in the upper 25% of the metric, while 'D' means they are in the lower 25%"
    ),
    div(" - TGT SHARE = % of team's targets in games player played"),
    div(" - AIR SHARE = % of team's air yards in games player played"),
    div(
      " - AIR = the average number of yards thrown toward a receiver when he is targeted"
    ),
    div(
      " - PTS = average fantasy points scored based on standard scoring rules (0 points per reception, 1 point per 10 yards receiving, 6 points per TD reception, -2 points per fumble lost; does not include points gained from rushing)"
    ),
    div(
      " - AVG PTS vs TOP 100 = average fantasy points scored relative to top 100 average fantasy points scored"
    )
  ),
  tags$span(style = "color:#777",
            div(
              "TABLE: KYLE CUILLA @KC_ANALYTICS  •  DATA: NFLFASTR"
            ))
)
```

```{r}
### Load font from Google Fonts
tags$link(href = "https://fonts.googleapis.com/css?family=Karla:400,700|Fira+Mono&display=fallback", rel = "stylesheet")
```

```{css}
/* Row and column borders */
.cell {
  box-shadow: inset 0 -1px 0 rgba(0, 0, 0, 0.07);
}

.border-left {
  border-left: 2px solid #666;
}

.border-right {
  border-right: 2px solid #666;
}

.last-row-border .cell {
  box-shadow: inset 0 -1px 0 #777;
}


/* Column hover formatting */
.header:hover,
.header[aria-sort="ascending"],
.header[aria-sort="descending"] {
  background-color: #dadada;
}

.header:active,
.header[aria-sort="ascending"],
.header[aria-sort="descending"] {
  background-color: #333;
  color: #fff;
}


/* Column header formatting */
.colheader {
  font-family: "Open Sans", sans-serif;
  font-size: 12px;
  border-bottom: 2px solid #555;
  text-transform: uppercase;
}

.groupheader {
  font-family: "Open Sans", sans-serif;
  font-size: 12px;
  text-transform: uppercase;
}


/* Number formatting */
.number {
  font-family: "Fira Mono", Consolas, Monaco, monospace;
  font-size: 12px;
  line-height: 30px;
  white-space: pre;
}

.number2 {
  font-family: "Fira Mono", Consolas, Monaco, monospace;
  font-size: 12px;
  line-height: 18px;
  white-space: pre;
}

/* Text formatting */
.fantasy-ratings {
  font-family: Karla, "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 12px;
}


/* target/air share column formatting */
.share-columns {
  margin-left: 3px;
  font-size: 13px;
  display: block;
}

/* Circle around WOPR rating */
.circle-border {
    border: 1.5px solid black;
    background-color: #FFFFFF;
    height: 30px;
    border-radius:50%;
    width: 30px;
    font-size: 13px;
  margin-left: 8px;
  margin-top: 2px;
}


/* Formatting for title above table */
.title {
  font-family: "Open Sans", sans-serif;
  font-size: 16px;
  margin: 16px 0;
}
```


